directories_config:
  open_pose_python: '/home/leo/rasberry_ws/src/openpose/build/python'
  open_pose_models: "/home/leo/rasberry_ws/src/openpose/models"
  gesture_classifier_model: "/home/leo/rasberry_ws/src/mesapro/config/classifier_model_3D_v2.joblib"
  training_set: '/home/leo/aa_data/new_data/training/'
  testing_set: '/home/leo/aa_data/new_data/testing/' 
###############################################  
action_recog_config:
  n_joints: 19       #19 body joints from openpose output (25 available)
  n_features: 36     #19 distances + 17 angles = 36 features
  posture_labels: ["no_gesture","both_arms","both_hands","crouched_down","left_arm","left_hand","picking","right_arm","right_hand"]
  motion_labels: ["not_defined","mostly_static", "moving"]
  orientation_labels: ["facing_the_robot", "giving_the_back", "left_side", "right_side"]
################################################
human_safety_config:
  hri_status: ["no_human","safety_hri","risky_hri","dangerous_hri"]
  audio_message: ["no_message","alert_UVC_danger","ask_for_next_action","ask_for_free_space","alert_approaching","alert_moving_away","alert_moving_to_goal"]
  safety_action: ["move_to_goal","approaching_to_human","moving_away_from_human","pause","wait_for_new_human_command","no_safety_action"]
  human_command: ["no_command","approach","move_away","stop","yes","no"]
  operation_mode: ["logistics","UV-C_treatment"]
###############################################
robot_config:
  action: ["moving_to_goal","approaching_to_human","moving_away_from_human","pause","waiting_for_new_human_command"]

