directories_config:
  open_pose_python: '/home/leo/rasberry_ws/src/mesapro/openpose/build/python'
  open_pose_models: "/home/leo/rasberry_ws/src/mesapro/openpose/models"
  gesture_classifier_model: "/home/leo/rasberry_ws/src/mesapro/config/classifier_model_3D_v2.joblib"
  training_set: '/home/leo/aa_data/new_data/training/'
  testing_set: '/home/leo/aa_data/new_data/testing/' 
###############################################  
action_recog_config:
  n_joints: 19       #19 body joints from openpose output (25 available)
  n_features: 36     #19 distances + 17 angels = 36 features
  posture_labels: ["no_gesture","both_arms","both_hands","crouched_down","left_arm","left_hand","picking","right_arm","right_hand"]
  motion_labels: ["not_defined","mostly_static", "approching_slowly", "approching_faster", "moving_away_slowly", "moving_away_faster"]
  orientation_labels: ["facing_the_robot", "giving_the_back", "left_side", "right_side"]
################################################
human_safety_config:
  hri_status: ["no_human","safe_interaction","risky_interact","critical_interact"]
  audio_message: ["no_message","ask_for_identity","ask_for_approaching","ask_for_continue_operation","ask_for_free_space","alert_before_row_transition","alert_while_approaching","alert_during_UVC"]
  safety_stop: ["normal_operation","reduced_speed","safety_stop"]
###############################################
